name: Build and Release on Stable Commit

on:
  push:
    branches:
      - main
    # только если сообщение коммита содержит "stable release" (регистронезависимо)
    paths-ignore:
      - '**/*.md'

jobs:
  build-and-release:
    if: contains(toLower(github.event.head_commit.message), 'stable release')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, darwin, freebsd, openbsd, netbsd, windows]
        goarch: [amd64, 386, arm, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Get short Git commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build ${{ matrix.goos }}/${{ matrix.goarch }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          VERSION: ${{ steps.vars.outputs.sha_short }}
        run: |
          mkdir -p dist
          EXT=""
          if [ "$GOOS" = "windows" ]; then EXT=".exe"; fi
          OUT="backup-redis_${GOOS}_${GOARCH}${EXT}"
          go build -o "dist/$OUT" -ldflags "-s -w -X main.version=$VERSION"
          file dist/$OUT || true

      - name: Create GitHub Release (latest)
        uses: softprops/action-gh-release@v2
        with:
          name: "Latest Stable Release"
          tag_name: "latest"
          prerelease: false
          draft: false
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

