# .github/workflows/release.yml
name: Build and Release Stable

on:
  push:
    branches:
      - main

# токену воркфлоу нужны права «contents: write», чтобы создать/обновить релиз
permissions:
  contents: write

jobs:
  build:
    # job запускается только если commit-message содержит 'stable release'
    if: contains(toJson(github.event.head_commit.message), 'stable release')
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - { goos: linux,  goarch: amd64 }
          - { goos: linux,  goarch: arm64 }
          - { goos: linux,  goarch: 386 }
          - { goos: linux,  goarch: arm }
          - { goos: darwin, goarch: amd64 }
          - { goos: darwin, goarch: arm64 }
          - { goos: freebsd, goarch: amd64 }
          - { goos: openbsd, goarch: amd64 }
          - { goos: netbsd, goarch: amd64 }

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # если go.mod отсутствует, создаём минимальный (можно удалить после добавления своего)
      - name: Init go.mod if absent
        run: |
          test -f go.mod || go mod init backup-redis

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build ${{ matrix.goos }}/${{ matrix.goarch }}
        env:
          GOOS:   ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0            # 👈 отключаем CGO → статический бинарник
          VERSION: ${{ github.sha }}
        run: |
          mkdir -p dist
          go build -o "dist/backup-redis_${GOOS}_${GOARCH}" \
                   -ldflags "-s -w -X main.version=$VERSION"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bin-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist-raw/

      - name: Publish GitHub Release (tag latest)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Stable Release"
          files: dist-raw/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
