# .github/workflows/release.yml
name: Build & Release Stable

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { goos: linux,  goarch: amd64 }
          - { goos: linux,  goarch: arm64 }
          - { goos: linux,  goarch: 386 }
          - { goos: linux,  goarch: arm }
          - { goos: darwin, goarch: amd64 }
          - { goos: darwin, goarch: arm64 }
          - { goos: freebsd, goarch: amd64 }
          - { goos: openbsd, goarch: amd64 }
          - { goos: netbsd, goarch: amd64 }

    steps:
      # выполняем только если сообщение коммита содержит "stable release"
      - name: Abort if commit ≠ stable release
        run: |
          echo "${{ github.event.head_commit.message }}" | grep -iq 'stable release' || exit 1

      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.22' }

      - name: Build ${{ matrix.goos }}/${{ matrix.goarch }}
        env:
          GOOS:   ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          VERSION: ${{ github.sha }}
        run: |
          mkdir -p dist
          go build -o "dist/backup-redis_${GOOS}_${GOARCH}" \
              -ldflags "-s -w -X main.version=$VERSION"

      - uses: actions/upload-artifact@v4
        with:
          name: "bin-${{ matrix.goos }}-${{ matrix.goarch }}"
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with: { path: dist-raw/ }

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Stable Release"
          files: dist-raw/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

