# .github/workflows/release.yml
# Build «redis-backup» статическими бинарниками (CGO_DISABLED),
# выпуск в GitHub Release «latest» при коммите с фразой `stable release`.

name: Build and Release Stable

on:
  push:
    branches:
      - main

# токену нужен доступ на запись (создаём/обновляем релиз)
permissions:
  contents: write

jobs:
  build:
    # Запуск только когда сообщение коммита содержит 'stable release'
    if: contains(toJson(github.event.head_commit.message), 'stable release')
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - { goos: linux,  goarch: amd64 }
          - { goos: linux,  goarch: arm64 }
          - { goos: linux,  goarch: 386 }
          - { goos: linux,  goarch: arm }
          - { goos: darwin, goarch: amd64 }
          - { goos: darwin, goarch: arm64 }
          - { goos: freebsd, goarch: amd64 }
          - { goos: openbsd, goarch: amd64 }
          - { goos: netbsd, goarch: amd64 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # создаём минимальный go.mod, если проекта ещё нет в модулях
      - name: Init go.mod if absent
        run: |
          test -f go.mod || go mod init redis-backup

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      # 🔨 СТАТИЧЕСКАЯ СБОРКА (CGO_ENABLED=0)
      - name: Build ${{ matrix.goos }}/${{ matrix.goarch }} (static)
        env:
          GOOS:   ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0                    # статический бинарь
          VERSION: ${{ github.sha }}
        run: |
          mkdir -p dist
          GOFLAGS="-trimpath" \
          go build -tags netgo,osusergo \
                   -ldflags "-s -w -X main.version=$VERSION" \
                   -o "dist/redis-backup_${GOOS}_${GOARCH}"

      # каждый артефакт — уникальное имя → нет 409 conflicts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bin-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist-raw/

      - name: Publish GitHub Release (tag latest)
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          name: "Latest Stable Release"
          prerelease: false
          files: dist-raw/**/*

